/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package YurtYonetimSistemi;

import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/**
 *
 * @author sayid
 */
public class OgrenciUcret extends javax.swing.JFrame {

    /**
     * Creates new form Ucret
     */
    public OgrenciUcret() {
        
        initComponents();
        
        updateUcretlerTablosu();   // yonetici tarafindan yeni bir ogrenci eklendiginde ucretler tablosuna yeni ogrencinin ucret bilgilerini ekler
        
        odemeyeniSil();         // ogrenci son odeme tarihinden 15 gun sonrasina kadar ucretini odemediyse kaydi silinecek
        
        ucretTarihleriniGuncelle(); // yeni aya girince ogrencini odeme durumunu odemedi diye gunceller
           
        
    }
    
    private void updateUcretlerTablosu(){
        
        MysqlConnector msql = new MysqlConnector();  
        Connection con = msql.connectorSender();     
        
        try{        //  Ogrenciler tablosuna yeni bir ogrenci eklendiginde ucretler tablosunu guncelleyen komutlar
            
            Statement stmt=con.createStatement(); 
            String Komut = String.format("insert ignore into ucretler(tcno, tarih) select tcno, kayittarihi from ogrenci;");
            stmt.executeUpdate(Komut); //  ucretler tablosunda olmayan ogrenciyi, yani yeni kayit olan ogrenciyi ogrenciler tablosundan ucretler
            Komut = String.format("update ucretler set odemeDurumu = 'Ödemedi' where tcno is not null and odemeDurumu is null;");//tablosuna ekler
            stmt.executeUpdate(Komut);
            
        }catch(Exception e){ 
            System.out.println(e);
            System.out.println("SQL EXception");
        }
        
    }

    private void odemeyeniSil(){
        
        MysqlConnector msql = new MysqlConnector();  
        Connection con = msql.connectorSender();     
        
        try{       
            
            Statement stmt=con.createStatement(); 
            
            
            String Komut = String.format("delete ogrenci, ucretler "  // ucretlerin son odeme tarihinden 15 gun sonra
                                          + "from ogrenci "           // ogrencinin kaydini siler
                                          + "inner join ucretler on ogrenci.tcno = ucretler.tcNo "
                                          + "where ucretler.tarih < curdate()-15 and odemeDurumu = 'Ödemedi';");
            
            stmt.executeUpdate(Komut);
            
        }catch(Exception e){ 
            System.out.println(e);
            System.out.println("SQL EXception");
        }
        
    }
    
     private void ucretTarihleriniGuncelle(){
        
        MysqlConnector msql = new MysqlConnector();  
        Connection con = msql.connectorSender();
        
        try{       
            
            Statement stmt=con.createStatement(); 
            
            String Komut = String.format("update ucretler "  // 30 gun sonra ogrencinin ucret odeme durumu odemedi ve son odeme tarihi de
                                           +"set tarih = date_add(tarih,INTERVAL 31 Day), odemeDurumu = 'Ödemedi' "  // 31 gun sonrasina
                                           +"where curdate() >= date_add(tarih, INTERVAL 30 Day);");                // degisecek
            
            stmt.executeUpdate(Komut);
            
        }catch(Exception e){
            System.out.println(e);
            System.out.println("SQL EXception");
        }
        
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtTcKimlik = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Sorgula = new javax.swing.JButton();
        tckimlikOde = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Borç Sorgula:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC Kimlik No.", "Ad", "Soyad", "Son Ödeme Tarihi", "Ödeme Durumu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTcKimlik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTcKimlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTcKimlikActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TC Kimlik No:");

        Sorgula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Sorgula.setText("Sorgula");
        Sorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SorgulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTcKimlik, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Sorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTcKimlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Sorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tckimlikOde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tckimlikOde.setText("Şimdi Öde");
        tckimlikOde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tckimlikOdeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ödemek istediğiniz Satırı seçerek Şimdi Öde butonuna tıklayınız");

        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("UYARI !! Yurt Ücretini Ödemeyen Öğrencilerin Son Ödeme Tarihinden 15 Gün Sonra Kaydı Silinecektir.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(tckimlikOde, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 266, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(tckimlikOde, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTcKimlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTcKimlikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTcKimlikActionPerformed

    private void SorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SorgulaActionPerformed
        
        update_table();
        
    }//GEN-LAST:event_SorgulaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new DenemeClass().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void odemeIslemi(){
        
        MysqlConnector msql = new MysqlConnector();
        Connection con = msql.connectorSender();
        
        DefaultTableModel Table = (DefaultTableModel)jTable1.getModel();
        int SelectedIndex = jTable1.getSelectedRow();    //  tabloda secilmis satirin indisini return eder
        
        String TCKimlik = Table.getValueAt(SelectedIndex, 0).toString(); // secilmis satirin ilk sifirinci sutununde olan tc kimligi return ede
        
        try{
            
            Statement stmt = con.createStatement();  // ogrenci simdi ode butununa tiklayinca odeme durumu odedi olacak
            String komut = String.format("Update ucretler set odemeDurumu = 'Ödedi' where tcno = %s ", TCKimlik);
            stmt.executeUpdate(komut);
            
            
           
        }catch(Exception e){
            System.out.println(e);
            System.out.println("SQL EXception");
        }
        
       
        
        update_table();
        
    }
    private void tckimlikOdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tckimlikOdeActionPerformed
        // TODO add your handling code here:
        
        int dialogButton = JOptionPane.showConfirmDialog(null, "Ödemek İstediğinize Emin Misiniz?",
                "Uyarı", JOptionPane.YES_NO_OPTION);

        if (dialogButton == JOptionPane.YES_OPTION) {
            
            odemeIslemi();
            JOptionPane.showMessageDialog(null, "Ödemeniz Başarıyla Gerçekleşti");
            
        } else {
            remove(dialogButton);
        }
       
    }//GEN-LAST:event_tckimlikOdeActionPerformed
        
    private void update_table()
    {
        MysqlConnector msql = new MysqlConnector();
        Connection con = msql.connectorSender();
        
        int column_count;
        
        try{
            
            Statement stmt = con.createStatement();
            String Komut = String.format("select ogrenci.tcno, ogrenci.ad, ogrenci.soyad, ucretler.tarih , ucretler.odemeDurumu\n" +
                                            "from ogrenci, ucretler\n" + // belirtilen bilgileri resultset olarak return eder // mysql komutu
                                            "where ogrenci.tcNo = ucretler.tcNo And ogrenci.tcno = %s", txtTcKimlik.getText());
            ResultSet ucretRS = stmt.executeQuery(Komut);
            ResultSetMetaData Rss = ucretRS.getMetaData();
            column_count = Rss.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            while (ucretRS.next()) {
                Vector v2 = new Vector();
                
                for(int a=1; a<=column_count; a++)
                {
                 
                    v2.add(ucretRS.getString("tcNo"));
                    v2.add(ucretRS.getString("ad"));               // bilgiler tabloya daha kolay eklensin diye bir vector objesi kullandim
                    v2.add(ucretRS.getString("soyad"));
                    v2.add(ucretRS.getString("tarih"));
                    v2.add(ucretRS.getString("odemeDurumu"));
            
                }
                
                df.addRow(v2);
            
                
            }
        } catch (SQLException e) {
            System.out.println(e);
            System.out.println("Exception");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OgrenciUcret.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OgrenciUcret.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OgrenciUcret.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OgrenciUcret.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OgrenciUcret().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sorgula;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton tckimlikOde;
    private javax.swing.JTextField txtTcKimlik;
    // End of variables declaration//GEN-END:variables
}

